### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by khitermedachraf**
In my first professional pull request, I set up the Linters configs, add basic HTML/CSS files and some styles in order to check how the Linters works and how to fix their errors, learn how to ignore unneeded files, and also add a README file to present my project and give necessary information about it.

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @khitermedachraf, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes:

- [x] Add a descriptive summary for your Pull Request.

## Highlights
- Professional Readme 👍 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by khitermedachraf** [comment]
Thank you so much for the Highlights and your support for me @sja-thedude.
I wanna ask you some further questions about non-technical questions like time management and what to do to have enough time to finish all work.
I feel I am entering the hole rabbit.
I'll Dm you in slack if you don't mind.

**Review by Donard97 — APPROVED** [review]
## Hi @khitermedachraf , 👋  

_Well done on implementing required changes from the other reviewer 👏 💯_ 

**Your project is complete!  There is nothing else to say other than... it's time to merge it 💪 🍾** 

## Congratulations! 🎉 🎉 🎉 

giphy (13)


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by khitermedachraf** [comment]
Thank You so much my code reviewers for your help and support.
You are the best💯💪

**Pull request merged**
